### ISSUE TITLE
The vira doesn't run after Oct.30 19:00 update

### ISSUE THREAD

**Issue by Tortes** [kg/ViramateInstaller#13]
### What's wrong?
The vira doesn't run after Oct.30 19:00 update, the vira shows u should login first.
All the function of vira stops work.

### What error messages (if any) are in the Chrome developer console? (Ctrl+Shift+I)
All the related messages appear as normal
`vms> External channel established
/#mypage:1 Failed to decode downloaded font: http://game.granbluefantasy.jp/user/nickname.woff
VM145:72 vms> Squelched`

### What version of Viramate and Viramate Installer are you using? (Appears in the Viramate Options page)
2018.10.1.2

### What version of Chrome are you using? (The first three lines of chrome://version/)

Google Chrome | 71.0.3578.20 (official build) beta （64 bit）
Revision| be2b6ea800808b865cd07ab76acf9e2a009c045a-refs/branch-heads/3578@{#254}

### What's your favorite color?
Black

**Comment by kg** [comment]
Thanks for the heads-up. This is intentional (Granblue's anti-cheat code changed) but it is unintended that the extension kind of misbehaves when it notices. I've pushed an update that addresses most of the issues with the automatic shutdown, but I don't have time to reverse engineer the new anti-cheat right now. Once I do (or if someone else does!) I can turn the extension back on.

**Comment by Tortes** [comment]
> Thanks for the heads-up. This is intentional (Granblue's anti-cheat code changed) but it is unintended that the extension kind of misbehaves when it notices. I've pushed an update that addresses most of the issues with the automatic shutdown, but I don't have time to reverse engineer the new anti-cheat right now. Once I do (or if someone else does!) I can turn the extension back on.

Thanks！Hope there will be someone to fix it

**Comment by Tortes** [comment]
(•̀ᴗ•́)و ̑̑
> Thanks
